export const directListingsLogicAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_nativeTokenWrapper", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "_msgData",
    outputs: [{ name: "", internalType: "bytes", type: "bytes" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "_msgSender",
    outputs: [{ name: "sender", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_listingId", internalType: "uint256", type: "uint256" },
      { name: "_buyer", internalType: "address", type: "address" },
      { name: "_toApprove", internalType: "bool", type: "bool" },
    ],
    name: "approveBuyerForListing",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_listingId", internalType: "uint256", type: "uint256" },
      { name: "_currency", internalType: "address", type: "address" },
      {
        name: "_pricePerTokenInCurrency",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "approveCurrencyForListing",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_listingId", internalType: "uint256", type: "uint256" },
      { name: "_buyFor", internalType: "address", type: "address" },
      { name: "_quantity", internalType: "uint256", type: "uint256" },
      { name: "_currency", internalType: "address", type: "address" },
      { name: "_expectedTotalPrice", internalType: "uint256", type: "uint256" },
    ],
    name: "buyFromListing",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [{ name: "_listingId", internalType: "uint256", type: "uint256" }],
    name: "cancelListing",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      {
        name: "_params",
        internalType: "struct IDirectListings.ListingParameters",
        type: "tuple",
        components: [
          { name: "assetContract", internalType: "address", type: "address" },
          { name: "tokenId", internalType: "uint256", type: "uint256" },
          { name: "quantity", internalType: "uint256", type: "uint256" },
          { name: "currency", internalType: "address", type: "address" },
          { name: "taxRate", internalType: "uint256", type: "uint256" },
          { name: "taxBeneficiary", internalType: "address", type: "address" },
          { name: "pricePerToken", internalType: "uint256", type: "uint256" },
          { name: "startTimestamp", internalType: "uint128", type: "uint128" },
          { name: "endTimestamp", internalType: "uint128", type: "uint128" },
          { name: "reserved", internalType: "bool", type: "bool" },
        ],
      },
    ],
    name: "createListing",
    outputs: [{ name: "listingId", internalType: "uint256", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_listingId", internalType: "uint256", type: "uint256" },
      { name: "_currency", internalType: "address", type: "address" },
    ],
    name: "currencyPriceForListing",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_listingId", internalType: "uint256", type: "uint256" }],
    name: "forecloseListing",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_startId", internalType: "uint256", type: "uint256" },
      { name: "_endId", internalType: "uint256", type: "uint256" },
    ],
    name: "getAllListings",
    outputs: [
      {
        name: "_allListings",
        internalType: "struct IDirectListings.Listing[]",
        type: "tuple[]",
        components: [
          { name: "listingId", internalType: "uint256", type: "uint256" },
          { name: "tokenId", internalType: "uint256", type: "uint256" },
          { name: "quantity", internalType: "uint256", type: "uint256" },
          { name: "pricePerToken", internalType: "uint256", type: "uint256" },
          { name: "startTimestamp", internalType: "uint128", type: "uint128" },
          { name: "endTimestamp", internalType: "uint128", type: "uint128" },
          { name: "listingCreator", internalType: "address", type: "address" },
          { name: "listingOwner", internalType: "address", type: "address" },
          { name: "assetContract", internalType: "address", type: "address" },
          { name: "currency", internalType: "address", type: "address" },
          { name: "taxRate", internalType: "uint256", type: "uint256" },
          { name: "taxBeneficiary", internalType: "address", type: "address" },
          {
            name: "tokenType",
            internalType: "enum IDirectListings.TokenType",
            type: "uint8",
          },
          {
            name: "status",
            internalType: "enum IDirectListings.Status",
            type: "uint8",
          },
          { name: "reserved", internalType: "bool", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_startId", internalType: "uint256", type: "uint256" },
      { name: "_endId", internalType: "uint256", type: "uint256" },
    ],
    name: "getAllValidListings",
    outputs: [
      {
        name: "_validListings",
        internalType: "struct IDirectListings.Listing[]",
        type: "tuple[]",
        components: [
          { name: "listingId", internalType: "uint256", type: "uint256" },
          { name: "tokenId", internalType: "uint256", type: "uint256" },
          { name: "quantity", internalType: "uint256", type: "uint256" },
          { name: "pricePerToken", internalType: "uint256", type: "uint256" },
          { name: "startTimestamp", internalType: "uint128", type: "uint128" },
          { name: "endTimestamp", internalType: "uint128", type: "uint128" },
          { name: "listingCreator", internalType: "address", type: "address" },
          { name: "listingOwner", internalType: "address", type: "address" },
          { name: "assetContract", internalType: "address", type: "address" },
          { name: "currency", internalType: "address", type: "address" },
          { name: "taxRate", internalType: "uint256", type: "uint256" },
          { name: "taxBeneficiary", internalType: "address", type: "address" },
          {
            name: "tokenType",
            internalType: "enum IDirectListings.TokenType",
            type: "uint8",
          },
          {
            name: "status",
            internalType: "enum IDirectListings.Status",
            type: "uint8",
          },
          { name: "reserved", internalType: "bool", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_listingId", internalType: "uint256", type: "uint256" }],
    name: "getListing",
    outputs: [
      {
        name: "listing",
        internalType: "struct IDirectListings.Listing",
        type: "tuple",
        components: [
          { name: "listingId", internalType: "uint256", type: "uint256" },
          { name: "tokenId", internalType: "uint256", type: "uint256" },
          { name: "quantity", internalType: "uint256", type: "uint256" },
          { name: "pricePerToken", internalType: "uint256", type: "uint256" },
          { name: "startTimestamp", internalType: "uint128", type: "uint128" },
          { name: "endTimestamp", internalType: "uint128", type: "uint128" },
          { name: "listingCreator", internalType: "address", type: "address" },
          { name: "listingOwner", internalType: "address", type: "address" },
          { name: "assetContract", internalType: "address", type: "address" },
          { name: "currency", internalType: "address", type: "address" },
          { name: "taxRate", internalType: "uint256", type: "uint256" },
          { name: "taxBeneficiary", internalType: "address", type: "address" },
          {
            name: "tokenType",
            internalType: "enum IDirectListings.TokenType",
            type: "uint8",
          },
          {
            name: "status",
            internalType: "enum IDirectListings.Status",
            type: "uint8",
          },
          { name: "reserved", internalType: "bool", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_listingId", internalType: "uint256", type: "uint256" },
      { name: "_buyer", internalType: "address", type: "address" },
    ],
    name: "isBuyerApprovedForListing",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_listingId", internalType: "uint256", type: "uint256" },
      { name: "_currency", internalType: "address", type: "address" },
    ],
    name: "isCurrencyApprovedForListing",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "totalListings",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_listingId", internalType: "uint256", type: "uint256" },
      {
        name: "_params",
        internalType: "struct IDirectListings.ListingParameters",
        type: "tuple",
        components: [
          { name: "assetContract", internalType: "address", type: "address" },
          { name: "tokenId", internalType: "uint256", type: "uint256" },
          { name: "quantity", internalType: "uint256", type: "uint256" },
          { name: "currency", internalType: "address", type: "address" },
          { name: "taxRate", internalType: "uint256", type: "uint256" },
          { name: "taxBeneficiary", internalType: "address", type: "address" },
          { name: "pricePerToken", internalType: "uint256", type: "uint256" },
          { name: "startTimestamp", internalType: "uint128", type: "uint128" },
          { name: "endTimestamp", internalType: "uint128", type: "uint128" },
          { name: "reserved", internalType: "bool", type: "bool" },
        ],
      },
    ],
    name: "updateListing",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "listingId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "buyer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "approved", internalType: "bool", type: "bool", indexed: false },
    ],
    name: "BuyerApprovedForListing",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "listingCreator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "listingId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
    ],
    name: "CancelledListing",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "listingId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "currency",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "pricePerToken",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "CurrencyApprovedForListing",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "listingCreator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "listingId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "assetContract",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "listing",
        internalType: "struct IDirectListings.Listing",
        type: "tuple",
        components: [
          { name: "listingId", internalType: "uint256", type: "uint256" },
          { name: "tokenId", internalType: "uint256", type: "uint256" },
          { name: "quantity", internalType: "uint256", type: "uint256" },
          { name: "pricePerToken", internalType: "uint256", type: "uint256" },
          { name: "startTimestamp", internalType: "uint128", type: "uint128" },
          { name: "endTimestamp", internalType: "uint128", type: "uint128" },
          { name: "listingCreator", internalType: "address", type: "address" },
          { name: "listingOwner", internalType: "address", type: "address" },
          { name: "assetContract", internalType: "address", type: "address" },
          { name: "currency", internalType: "address", type: "address" },
          { name: "taxRate", internalType: "uint256", type: "uint256" },
          { name: "taxBeneficiary", internalType: "address", type: "address" },
          {
            name: "tokenType",
            internalType: "enum IDirectListings.TokenType",
            type: "uint8",
          },
          {
            name: "status",
            internalType: "enum IDirectListings.Status",
            type: "uint8",
          },
          { name: "reserved", internalType: "bool", type: "bool" },
        ],
        indexed: false,
      },
    ],
    name: "NewListing",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "listingCreator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "listingId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "assetContract",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "tokenId",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "buyer",
        internalType: "address",
        type: "address",
        indexed: false,
      },
      {
        name: "quantityBought",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "totalPricePaid",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "NewSale",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "listingId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "sender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "receiver",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "flowRate",
        internalType: "int96",
        type: "int96",
        indexed: false,
      },
    ],
    name: "UpdateAdFLowRate",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "listingCreator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "listingId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "assetContract",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "listing",
        internalType: "struct IDirectListings.Listing",
        type: "tuple",
        components: [
          { name: "listingId", internalType: "uint256", type: "uint256" },
          { name: "tokenId", internalType: "uint256", type: "uint256" },
          { name: "quantity", internalType: "uint256", type: "uint256" },
          { name: "pricePerToken", internalType: "uint256", type: "uint256" },
          { name: "startTimestamp", internalType: "uint128", type: "uint128" },
          { name: "endTimestamp", internalType: "uint128", type: "uint128" },
          { name: "listingCreator", internalType: "address", type: "address" },
          { name: "listingOwner", internalType: "address", type: "address" },
          { name: "assetContract", internalType: "address", type: "address" },
          { name: "currency", internalType: "address", type: "address" },
          { name: "taxRate", internalType: "uint256", type: "uint256" },
          { name: "taxBeneficiary", internalType: "address", type: "address" },
          {
            name: "tokenType",
            internalType: "enum IDirectListings.TokenType",
            type: "uint8",
          },
          {
            name: "status",
            internalType: "enum IDirectListings.Status",
            type: "uint8",
          },
          { name: "reserved", internalType: "bool", type: "bool" },
        ],
        indexed: false,
      },
    ],
    name: "UpdatedListing",
  },
  {
    type: "error",
    inputs: [
      { name: "expected", internalType: "uint256", type: "uint256" },
      { name: "actual", internalType: "uint256", type: "uint256" },
    ],
    name: "CurrencyTransferLibMismatchedValue",
  },
] as const;
